In [2]:
import gensim.downloader as api

wv = api.load("word2vec-google-news-300")

In [3]:
wv.similarity(w1 = 'great', w2 = 'good')

0.7291509

In [4]:
wv.most_similar("friend")

[('pal', 0.7476357221603394),
 ('friends', 0.7098035216331482),
 ('buddy', 0.6972494721412659),
 ('dear_friend', 0.6960037350654602),
 ('acquaintance', 0.6843010783195496),
 ('cousin', 0.6713200211524963),
 ('girlfriend', 0.6226293444633484),
 ('colleague', 0.6204894781112671),
 ('uncle', 0.6120922565460205),
 ('roommate', 0.611858069896698)]

In [5]:
wv.most_similar(positive = ['king', 'woman'], negative = ['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674735069275),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377322435379028),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134939193726),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411403656006)]

In [8]:
wv.doesnt_match(['facebook', 'telegram', 'google', 'twitter', 'dog'])

'dog'

In [9]:
glv = api.load('glove-twitter-25')

[==================================================] 100.0% 104.8/104.8MB downloaded


In [10]:
glv.most_similar("friend")

[('sister', 0.9584945440292358),
 ('mom', 0.9529940485954285),
 ('you', 0.9425639510154724),
 ('girl', 0.9419866800308228),
 ('boyfriend', 0.9400219321250916),
 ('dad', 0.9384721517562866),
 ('friends', 0.9310929775238037),
 ('mother', 0.9293221831321716),
 ('brother', 0.928379237651825),
 ('girlfriend', 0.9261802434921265)]

In [12]:
import pandas as pd

df = pd.read_csv("Fake_Real_Data.csv")
df.shape

(9900, 2)

In [13]:
df.head(5)

Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [14]:
df.label.value_counts()

Fake    5000
Real    4900
Name: label, dtype: int64

In [15]:
df['label_num'] = df.label.map({
    'Fake': 0,
    'Real': 1
})
df.head(5)

Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [21]:
import spacy
nlp = spacy.load('en_core_web_lg')

def preprocess_and_vectorize(text):
    doc = nlp(text)
    
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    return wv.get_mean_vector(filtered_tokens)

In [18]:
v1 = wv['worry']
v2 = wv['understand']

import numpy as np
np.mean([v1,v2], axis = 0)

array([ 0.00976562, -0.00561523, -0.08905029,  0.01330566, -0.2709961 ,
        0.14746094,  0.3408203 , -0.01840591,  0.15161133, -0.06945801,
       -0.05749512, -0.17822266, -0.03805542,  0.08730698, -0.22216797,
        0.2578125 ,  0.06481934,  0.29589844,  0.00537109, -0.1875    ,
       -0.1159668 ,  0.0715332 ,  0.08691406,  0.05912399,  0.18359375,
        0.17687988,  0.09130859, -0.22705078,  0.10522461, -0.2475586 ,
       -0.02436638,  0.01245117, -0.06616211, -0.02587891,  0.13476562,
       -0.02604675,  0.06582642,  0.0612793 ,  0.07128906,  0.13867188,
        0.03234863, -0.03295898,  0.17736816, -0.08789062, -0.21777344,
       -0.11010742, -0.08728027, -0.01922607, -0.04943848,  0.05273438,
       -0.18066406,  0.13122559, -0.07498932, -0.10064697, -0.01171875,
        0.12963867, -0.10766602, -0.14624023,  0.11303711, -0.12280273,
       -0.03540039,  0.03601074, -0.01379395,  0.01042175,  0.1105957 ,
       -0.03820801, -0.20751953,  0.1352539 , -0.0625    , -0.01

In [23]:
wv.get_mean_vector(['worry', 'understand'])

array([ 0.00235079, -0.00284596, -0.03638233,  0.00413919, -0.10635224,
        0.05758579,  0.13348952, -0.00689176,  0.05995331, -0.02875906,
       -0.02279907, -0.06939262, -0.01549996,  0.03538099, -0.0873947 ,
        0.10044542,  0.02490648,  0.11501945,  0.00442711, -0.07228819,
       -0.04447255,  0.02785169,  0.03338735,  0.02222995,  0.07053161,
        0.06723307,  0.03483712, -0.0873695 ,  0.04152397, -0.0969665 ,
       -0.00914938,  0.00555944, -0.0277799 , -0.00701522,  0.05281431,
       -0.01066206,  0.02466576,  0.02378148,  0.0279402 ,  0.05527755,
        0.01359304, -0.01062085,  0.06734448, -0.03492254, -0.08421434,
       -0.04324378, -0.03578918, -0.00817786, -0.02093195,  0.01856531,
       -0.07064191,  0.05023994, -0.03036207, -0.0412168 , -0.00684169,
        0.05189689, -0.04097777, -0.05789134,  0.044417  , -0.0470418 ,
       -0.01475445,  0.01373999, -0.00459672,  0.00419459,  0.04307397,
       -0.01500929, -0.08037488,  0.05358911, -0.0211829 , -0.00

In [22]:
preprocess_and_vectorize("Don't worry if you don't understand")

array([ 0.00235079, -0.00284596, -0.03638233,  0.00413919, -0.10635224,
        0.05758579,  0.13348952, -0.00689176,  0.05995331, -0.02875906,
       -0.02279907, -0.06939262, -0.01549996,  0.03538099, -0.0873947 ,
        0.10044542,  0.02490648,  0.11501945,  0.00442711, -0.07228819,
       -0.04447255,  0.02785169,  0.03338735,  0.02222995,  0.07053161,
        0.06723307,  0.03483712, -0.0873695 ,  0.04152397, -0.0969665 ,
       -0.00914938,  0.00555944, -0.0277799 , -0.00701522,  0.05281431,
       -0.01066206,  0.02466576,  0.02378148,  0.0279402 ,  0.05527755,
        0.01359304, -0.01062085,  0.06734448, -0.03492254, -0.08421434,
       -0.04324378, -0.03578918, -0.00817786, -0.02093195,  0.01856531,
       -0.07064191,  0.05023994, -0.03036207, -0.0412168 , -0.00684169,
        0.05189689, -0.04097777, -0.05789134,  0.044417  , -0.0470418 ,
       -0.01475445,  0.01373999, -0.00459672,  0.00419459,  0.04307397,
       -0.01500929, -0.08037488,  0.05358911, -0.0211829 , -0.00

In [24]:
df['vector'] = df.Text.apply(preprocess_and_vectorize)
df.head()

Text label  label_num  \
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0   
1  U.S. conservative leader optimistic of common ...  Real          1   
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1   
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0   
4  Democrats say Trump agrees to work on immigrat...  Real          1   

                                              vector  
0  [0.008238997, 0.01985944, -0.010530562, 0.0336...  
1  [0.00995244, 0.007760858, 0.0022168206, 0.0172...  
2  [0.01825762, 0.0061956076, -0.005815002, 0.037...  
3  [0.012362897, 0.012731943, 0.00016021932, 0.02...  
4  [-0.002259819, 0.01164962, 0.0036556108, 0.028...